# Generated by Django 4.1.3 on 2022-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_postal_code_order_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
